name: dbatools-lab-container-test

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs the docker compose up
      - name: Containers Be ready
        run: |
          cd tests\setup\
          docker-compose up -d
          docker ps -a 
        shell: pwsh

      - name: Install and cache PowerShell modules
        uses: potatoqualitee/psmodulecache@v4
        with:
          modules-to-cache: PSFramework, dbachecks, dbatools, Pester:4.10.1

      - name: Test the connection to the containers
        run: |
          Import-Module dbachecks 
          $secStringPassword = ConvertTo-SecureString -String 'dbatools.IO' -AsPlainText -Force
          $sqlcred = New-Object System.Management.Automation.PSCredential ('sqladmin', $secStringPassword)
          $PSDefaultParameterValues = @{'*:SqlCredential' = $sqlcred;'*:WarningAction' = 'Stop'}
          Set-DbcConfig -Name policy.connection.authscheme -Value SQL 
          Set-DbcConfig -Name skip.connection.ping -Value $true 
          Set-DbcConfig -Name skip.connection.remoting -Value $true
          Invoke-DbcCheck -Check InstanceConnection -SqlInstance 'localhost,15592','localhost,15593'
        shell: pwsh

      - name: Clone the Book Repo 
        run: | 
          mkdir book
          cd book
          git clone https://oauth2:${{ secrets.GITLABTOKEN }}@git.manning.com/agileauthor/leMaire.git 
          ls -R

      - name: Get some code from the book and test it
        run: | 
          cd book
          Invoke-Pester ../tests/bookcode.tests.ps1
        shell: pwsh
